// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/market.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_CheckMarket_FullMethodName = "/market.MarketService/CheckMarket"
	MarketService_BuyAsset_FullMethodName    = "/market.MarketService/BuyAsset"
	MarketService_SellAsset_FullMethodName   = "/market.MarketService/SellAsset"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	CheckMarket(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketResponse], error)
	BuyAsset(ctx context.Context, in *BuyAssetRequest, opts ...grpc.CallOption) (*BuyAssetResponse, error)
	SellAsset(ctx context.Context, in *SellAssetRequest, opts ...grpc.CallOption) (*SellAssetResponse, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) CheckMarket(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[0], MarketService_CheckMarket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MarketRequest, MarketResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketService_CheckMarketClient = grpc.ServerStreamingClient[MarketResponse]

func (c *marketServiceClient) BuyAsset(ctx context.Context, in *BuyAssetRequest, opts ...grpc.CallOption) (*BuyAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyAssetResponse)
	err := c.cc.Invoke(ctx, MarketService_BuyAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) SellAsset(ctx context.Context, in *SellAssetRequest, opts ...grpc.CallOption) (*SellAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellAssetResponse)
	err := c.cc.Invoke(ctx, MarketService_SellAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
type MarketServiceServer interface {
	CheckMarket(*MarketRequest, grpc.ServerStreamingServer[MarketResponse]) error
	BuyAsset(context.Context, *BuyAssetRequest) (*BuyAssetResponse, error)
	SellAsset(context.Context, *SellAssetRequest) (*SellAssetResponse, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) CheckMarket(*MarketRequest, grpc.ServerStreamingServer[MarketResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CheckMarket not implemented")
}
func (UnimplementedMarketServiceServer) BuyAsset(context.Context, *BuyAssetRequest) (*BuyAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyAsset not implemented")
}
func (UnimplementedMarketServiceServer) SellAsset(context.Context, *SellAssetRequest) (*SellAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellAsset not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_CheckMarket_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MarketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).CheckMarket(m, &grpc.GenericServerStream[MarketRequest, MarketResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketService_CheckMarketServer = grpc.ServerStreamingServer[MarketResponse]

func _MarketService_BuyAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).BuyAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_BuyAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).BuyAsset(ctx, req.(*BuyAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_SellAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).SellAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_SellAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).SellAsset(ctx, req.(*SellAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyAsset",
			Handler:    _MarketService_BuyAsset_Handler,
		},
		{
			MethodName: "SellAsset",
			Handler:    _MarketService_SellAsset_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckMarket",
			Handler:       _MarketService_CheckMarket_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/market.proto",
}
