// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/market.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Petición: solo dejamos que el cliente indique el intervalo en segundos
type MarketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // default 4 si viene 0 o negativo
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarketRequest) Reset() {
	*x = MarketRequest{}
	mi := &file_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequest) ProtoMessage() {}

func (x *MarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequest.ProtoReflect.Descriptor instead.
func (*MarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *MarketRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// Respuesta por cada “tick” de mercado
type MarketAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Volatility    float64                `protobuf:"fixed64,6,opt,name=volatility,proto3" json:"volatility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketAsset) Reset() {
	*x = MarketAsset{}
	mi := &file_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketAsset) ProtoMessage() {}

func (x *MarketAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketAsset.ProtoReflect.Descriptor instead.
func (*MarketAsset) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *MarketAsset) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarketAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketAsset) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketAsset) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *MarketAsset) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

type MarketResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMillis int64                  `protobuf:"varint,1,opt,name=timestamp_unix_millis,json=timestampUnixMillis,proto3" json:"timestamp_unix_millis,omitempty"`
	Assets              []*MarketAsset         `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MarketResponse) Reset() {
	*x = MarketResponse{}
	mi := &file_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketResponse) ProtoMessage() {}

func (x *MarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketResponse.ProtoReflect.Descriptor instead.
func (*MarketResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{2}
}

func (x *MarketResponse) GetTimestampUnixMillis() int64 {
	if x != nil {
		return x.TimestampUnixMillis
	}
	return 0
}

func (x *MarketResponse) GetAssets() []*MarketAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

var File_proto_market_proto protoreflect.FileDescriptor

const file_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x12proto/market.proto\x12\x06market\":\n" +
	"\rMarketRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\"\x9e\x01\n" +
	"\vMarketAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"base_price\x18\x05 \x01(\x01R\tbasePrice\x12\x1e\n" +
	"\n" +
	"volatility\x18\x06 \x01(\x01R\n" +
	"volatility\"q\n" +
	"\x0eMarketResponse\x122\n" +
	"\x15timestamp_unix_millis\x18\x01 \x01(\x03R\x13timestampUnixMillis\x12+\n" +
	"\x06assets\x18\x02 \x03(\v2\x13.market.MarketAssetR\x06assets2O\n" +
	"\rMarketService\x12>\n" +
	"\vCheckMarket\x12\x15.market.MarketRequest\x1a\x16.market.MarketResponse0\x01BFZDgithub.com/jaftdelgado/aureum-services/MarketGRPCService/proto;protob\x06proto3"

var (
	file_proto_market_proto_rawDescOnce sync.Once
	file_proto_market_proto_rawDescData []byte
)

func file_proto_market_proto_rawDescGZIP() []byte {
	file_proto_market_proto_rawDescOnce.Do(func() {
		file_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)))
	})
	return file_proto_market_proto_rawDescData
}

var file_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_market_proto_goTypes = []any{
	(*MarketRequest)(nil),  // 0: market.MarketRequest
	(*MarketAsset)(nil),    // 1: market.MarketAsset
	(*MarketResponse)(nil), // 2: market.MarketResponse
}
var file_proto_market_proto_depIdxs = []int32{
	1, // 0: market.MarketResponse.assets:type_name -> market.MarketAsset
	0, // 1: market.MarketService.CheckMarket:input_type -> market.MarketRequest
	2, // 2: market.MarketService.CheckMarket:output_type -> market.MarketResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_market_proto_init() }
func file_proto_market_proto_init() {
	if File_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_market_proto_goTypes,
		DependencyIndexes: file_proto_market_proto_depIdxs,
		MessageInfos:      file_proto_market_proto_msgTypes,
	}.Build()
	File_proto_market_proto = out.File
	file_proto_market_proto_goTypes = nil
	file_proto_market_proto_depIdxs = nil
}
