// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/market.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TeamPublicId    string                 `protobuf:"bytes,2,opt,name=team_public_id,json=teamPublicId,proto3" json:"team_public_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarketRequest) Reset() {
	*x = MarketRequest{}
	mi := &file_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequest) ProtoMessage() {}

func (x *MarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequest.ProtoReflect.Descriptor instead.
func (*MarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *MarketRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *MarketRequest) GetTeamPublicId() string {
	if x != nil {
		return x.TeamPublicId
	}
	return ""
}

type MarketAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Volatility    float64                `protobuf:"fixed64,6,opt,name=volatility,proto3" json:"volatility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketAsset) Reset() {
	*x = MarketAsset{}
	mi := &file_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketAsset) ProtoMessage() {}

func (x *MarketAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketAsset.ProtoReflect.Descriptor instead.
func (*MarketAsset) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *MarketAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarketAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketAsset) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketAsset) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *MarketAsset) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

type MarketResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMillis int64                  `protobuf:"varint,1,opt,name=timestamp_unix_millis,json=timestampUnixMillis,proto3" json:"timestamp_unix_millis,omitempty"`
	Assets              []*MarketAsset         `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MarketResponse) Reset() {
	*x = MarketResponse{}
	mi := &file_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketResponse) ProtoMessage() {}

func (x *MarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketResponse.ProtoReflect.Descriptor instead.
func (*MarketResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{2}
}

func (x *MarketResponse) GetTimestampUnixMillis() int64 {
	if x != nil {
		return x.TimestampUnixMillis
	}
	return 0
}

func (x *MarketResponse) GetAssets() []*MarketAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type BuyAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamPublicId  string                 `protobuf:"bytes,1,opt,name=team_public_id,json=teamPublicId,proto3" json:"team_public_id,omitempty"`    // uuid del team
	AssetPublicId string                 `protobuf:"bytes,2,opt,name=asset_public_id,json=assetPublicId,proto3" json:"asset_public_id,omitempty"` // uuid del asset
	UserPublicId  string                 `protobuf:"bytes,3,opt,name=user_public_id,json=userPublicId,proto3" json:"user_public_id,omitempty"`    // uuid del usuario que compra
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                                // cantidad comprada
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                      // precio al que se ejecuta la compra
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAssetRequest) Reset() {
	*x = BuyAssetRequest{}
	mi := &file_proto_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAssetRequest) ProtoMessage() {}

func (x *BuyAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAssetRequest.ProtoReflect.Descriptor instead.
func (*BuyAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{3}
}

func (x *BuyAssetRequest) GetTeamPublicId() string {
	if x != nil {
		return x.TeamPublicId
	}
	return ""
}

func (x *BuyAssetRequest) GetAssetPublicId() string {
	if x != nil {
		return x.AssetPublicId
	}
	return ""
}

func (x *BuyAssetRequest) GetUserPublicId() string {
	if x != nil {
		return x.UserPublicId
	}
	return ""
}

func (x *BuyAssetRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyAssetRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyAssetNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPublicId  string                 `protobuf:"bytes,1,opt,name=user_public_id,json=userPublicId,proto3" json:"user_public_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAssetNotification) Reset() {
	*x = BuyAssetNotification{}
	mi := &file_proto_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAssetNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAssetNotification) ProtoMessage() {}

func (x *BuyAssetNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAssetNotification.ProtoReflect.Descriptor instead.
func (*BuyAssetNotification) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{4}
}

func (x *BuyAssetNotification) GetUserPublicId() string {
	if x != nil {
		return x.UserPublicId
	}
	return ""
}

func (x *BuyAssetNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BuyAssetResponse struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	MovementPublicId    string                  `protobuf:"bytes,1,opt,name=movement_public_id,json=movementPublicId,proto3" json:"movement_public_id,omitempty"`
	TransactionPublicId string                  `protobuf:"bytes,2,opt,name=transaction_public_id,json=transactionPublicId,proto3" json:"transaction_public_id,omitempty"`
	TransactionPrice    float64                 `protobuf:"fixed64,3,opt,name=transaction_price,json=transactionPrice,proto3" json:"transaction_price,omitempty"`
	Quantity            float64                 `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Notifications       []*BuyAssetNotification `protobuf:"bytes,5,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BuyAssetResponse) Reset() {
	*x = BuyAssetResponse{}
	mi := &file_proto_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAssetResponse) ProtoMessage() {}

func (x *BuyAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAssetResponse.ProtoReflect.Descriptor instead.
func (*BuyAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{5}
}

func (x *BuyAssetResponse) GetMovementPublicId() string {
	if x != nil {
		return x.MovementPublicId
	}
	return ""
}

func (x *BuyAssetResponse) GetTransactionPublicId() string {
	if x != nil {
		return x.TransactionPublicId
	}
	return ""
}

func (x *BuyAssetResponse) GetTransactionPrice() float64 {
	if x != nil {
		return x.TransactionPrice
	}
	return 0
}

func (x *BuyAssetResponse) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyAssetResponse) GetNotifications() []*BuyAssetNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type SellAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamPublicId  string                 `protobuf:"bytes,1,opt,name=team_public_id,json=teamPublicId,proto3" json:"team_public_id,omitempty"`
	AssetPublicId string                 `protobuf:"bytes,2,opt,name=asset_public_id,json=assetPublicId,proto3" json:"asset_public_id,omitempty"`
	UserPublicId  string                 `protobuf:"bytes,3,opt,name=user_public_id,json=userPublicId,proto3" json:"user_public_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellAssetRequest) Reset() {
	*x = SellAssetRequest{}
	mi := &file_proto_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellAssetRequest) ProtoMessage() {}

func (x *SellAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellAssetRequest.ProtoReflect.Descriptor instead.
func (*SellAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{6}
}

func (x *SellAssetRequest) GetTeamPublicId() string {
	if x != nil {
		return x.TeamPublicId
	}
	return ""
}

func (x *SellAssetRequest) GetAssetPublicId() string {
	if x != nil {
		return x.AssetPublicId
	}
	return ""
}

func (x *SellAssetRequest) GetUserPublicId() string {
	if x != nil {
		return x.UserPublicId
	}
	return ""
}

func (x *SellAssetRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellAssetRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SellAssetResponse struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	MovementPublicId    string                  `protobuf:"bytes,1,opt,name=movement_public_id,json=movementPublicId,proto3" json:"movement_public_id,omitempty"`
	TransactionPublicId string                  `protobuf:"bytes,2,opt,name=transaction_public_id,json=transactionPublicId,proto3" json:"transaction_public_id,omitempty"`
	TransactionPrice    float64                 `protobuf:"fixed64,3,opt,name=transaction_price,json=transactionPrice,proto3" json:"transaction_price,omitempty"`
	Quantity            float64                 `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Notifications       []*BuyAssetNotification `protobuf:"bytes,5,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SellAssetResponse) Reset() {
	*x = SellAssetResponse{}
	mi := &file_proto_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellAssetResponse) ProtoMessage() {}

func (x *SellAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellAssetResponse.ProtoReflect.Descriptor instead.
func (*SellAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{7}
}

func (x *SellAssetResponse) GetMovementPublicId() string {
	if x != nil {
		return x.MovementPublicId
	}
	return ""
}

func (x *SellAssetResponse) GetTransactionPublicId() string {
	if x != nil {
		return x.TransactionPublicId
	}
	return ""
}

func (x *SellAssetResponse) GetTransactionPrice() float64 {
	if x != nil {
		return x.TransactionPrice
	}
	return 0
}

func (x *SellAssetResponse) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellAssetResponse) GetNotifications() []*BuyAssetNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

var File_proto_market_proto protoreflect.FileDescriptor

const file_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x12proto/market.proto\x12\x06market\"`\n" +
	"\rMarketRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\x12$\n" +
	"\x0eteam_public_id\x18\x02 \x01(\tR\fteamPublicId\"\x9e\x01\n" +
	"\vMarketAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"base_price\x18\x05 \x01(\x01R\tbasePrice\x12\x1e\n" +
	"\n" +
	"volatility\x18\x06 \x01(\x01R\n" +
	"volatility\"q\n" +
	"\x0eMarketResponse\x122\n" +
	"\x15timestamp_unix_millis\x18\x01 \x01(\x03R\x13timestampUnixMillis\x12+\n" +
	"\x06assets\x18\x02 \x03(\v2\x13.market.MarketAssetR\x06assets\"\xb7\x01\n" +
	"\x0fBuyAssetRequest\x12$\n" +
	"\x0eteam_public_id\x18\x01 \x01(\tR\fteamPublicId\x12&\n" +
	"\x0fasset_public_id\x18\x02 \x01(\tR\rassetPublicId\x12$\n" +
	"\x0euser_public_id\x18\x03 \x01(\tR\fuserPublicId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"V\n" +
	"\x14BuyAssetNotification\x12$\n" +
	"\x0euser_public_id\x18\x01 \x01(\tR\fuserPublicId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x02\n" +
	"\x10BuyAssetResponse\x12,\n" +
	"\x12movement_public_id\x18\x01 \x01(\tR\x10movementPublicId\x122\n" +
	"\x15transaction_public_id\x18\x02 \x01(\tR\x13transactionPublicId\x12+\n" +
	"\x11transaction_price\x18\x03 \x01(\x01R\x10transactionPrice\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12B\n" +
	"\rnotifications\x18\x05 \x03(\v2\x1c.market.BuyAssetNotificationR\rnotifications\"\xb8\x01\n" +
	"\x10SellAssetRequest\x12$\n" +
	"\x0eteam_public_id\x18\x01 \x01(\tR\fteamPublicId\x12&\n" +
	"\x0fasset_public_id\x18\x02 \x01(\tR\rassetPublicId\x12$\n" +
	"\x0euser_public_id\x18\x03 \x01(\tR\fuserPublicId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\x82\x02\n" +
	"\x11SellAssetResponse\x12,\n" +
	"\x12movement_public_id\x18\x01 \x01(\tR\x10movementPublicId\x122\n" +
	"\x15transaction_public_id\x18\x02 \x01(\tR\x13transactionPublicId\x12+\n" +
	"\x11transaction_price\x18\x03 \x01(\x01R\x10transactionPrice\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12B\n" +
	"\rnotifications\x18\x05 \x03(\v2\x1c.market.BuyAssetNotificationR\rnotifications2\xd0\x01\n" +
	"\rMarketService\x12>\n" +
	"\vCheckMarket\x12\x15.market.MarketRequest\x1a\x16.market.MarketResponse0\x01\x12=\n" +
	"\bBuyAsset\x12\x17.market.BuyAssetRequest\x1a\x18.market.BuyAssetResponse\x12@\n" +
	"\tSellAsset\x12\x18.market.SellAssetRequest\x1a\x19.market.SellAssetResponseBFZDgithub.com/jaftdelgado/aureum-services/MarketGRPCService/proto;protob\x06proto3"

var (
	file_proto_market_proto_rawDescOnce sync.Once
	file_proto_market_proto_rawDescData []byte
)

func file_proto_market_proto_rawDescGZIP() []byte {
	file_proto_market_proto_rawDescOnce.Do(func() {
		file_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)))
	})
	return file_proto_market_proto_rawDescData
}

var file_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_market_proto_goTypes = []any{
	(*MarketRequest)(nil),        // 0: market.MarketRequest
	(*MarketAsset)(nil),          // 1: market.MarketAsset
	(*MarketResponse)(nil),       // 2: market.MarketResponse
	(*BuyAssetRequest)(nil),      // 3: market.BuyAssetRequest
	(*BuyAssetNotification)(nil), // 4: market.BuyAssetNotification
	(*BuyAssetResponse)(nil),     // 5: market.BuyAssetResponse
	(*SellAssetRequest)(nil),     // 6: market.SellAssetRequest
	(*SellAssetResponse)(nil),    // 7: market.SellAssetResponse
}
var file_proto_market_proto_depIdxs = []int32{
	1, // 0: market.MarketResponse.assets:type_name -> market.MarketAsset
	4, // 1: market.BuyAssetResponse.notifications:type_name -> market.BuyAssetNotification
	4, // 2: market.SellAssetResponse.notifications:type_name -> market.BuyAssetNotification
	0, // 3: market.MarketService.CheckMarket:input_type -> market.MarketRequest
	3, // 4: market.MarketService.BuyAsset:input_type -> market.BuyAssetRequest
	6, // 5: market.MarketService.SellAsset:input_type -> market.SellAssetRequest
	2, // 6: market.MarketService.CheckMarket:output_type -> market.MarketResponse
	5, // 7: market.MarketService.BuyAsset:output_type -> market.BuyAssetResponse
	7, // 8: market.MarketService.SellAsset:output_type -> market.SellAssetResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_market_proto_init() }
func file_proto_market_proto_init() {
	if File_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_market_proto_goTypes,
		DependencyIndexes: file_proto_market_proto_depIdxs,
		MessageInfos:      file_proto_market_proto_msgTypes,
	}.Build()
	File_proto_market_proto = out.File
	file_proto_market_proto_goTypes = nil
	file_proto_market_proto_depIdxs = nil
}
