// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamService.Data;

#nullable disable

namespace TeamService.Migrations
{
    [DbContext(typeof(TeamDbContext))]
    [Migration("20251113034308_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "currency_enum", "currency_enum", new[] { "usd", "eur", "mxn" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "thick_speed_enum", "thick_speed_enum", new[] { "high", "medium", "low" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_fee_enum", "transaction_fee_enum", new[] { "high", "medium", "low", "disabled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "volatility_enum", "volatility_enum", new[] { "high", "medium", "low", "disabled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamService.Models.MarketConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("configid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<bool?>("AllowShortSelling")
                        .HasColumnType("boolean")
                        .HasColumnName("allowshortselling");

                    b.Property<int>("CrashImpact")
                        .HasColumnType("integer")
                        .HasColumnName("crashimpact");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<int>("DividendImpact")
                        .HasColumnType("integer")
                        .HasColumnName("dividendimpact");

                    b.Property<int>("EventFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("eventfrequency");

                    b.Property<double>("InitialCash")
                        .HasColumnType("double precision")
                        .HasColumnName("initialcash");

                    b.Property<int>("MarketLiquidity")
                        .HasColumnType("integer")
                        .HasColumnName("marketliquidity");

                    b.Property<int>("MarketVolatility")
                        .HasColumnType("integer")
                        .HasColumnName("marketvolatility");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<int>("ThickSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("thickspeed");

                    b.Property<int>("TransactionFee")
                        .HasColumnType("integer")
                        .HasColumnName("transactionfee");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("ConfigId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("marketconfiguration", "public");
                });

            modelBuilder.Entity("TeamService.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("description");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professorid");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("teamname");

                    b.Property<string>("TeamPic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("teampic");

                    b.HasKey("TeamId");

                    b.ToTable("team", "public");
                });

            modelBuilder.Entity("TeamService.Models.TeamAsset", b =>
                {
                    b.Property<int>("TeamAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teamassetid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamAssetId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("assetid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.HasKey("TeamAssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("TeamId");

                    b.ToTable("teamasset", "public");
                });

            modelBuilder.Entity("TeamService.Models.TeamMembership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("membershipid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipId"));

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joinedat");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("MembershipId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("teammembership", "public");
                });

            modelBuilder.Entity("TeamService.Models.MarketConfiguration", b =>
                {
                    b.HasOne("TeamService.Models.Team", "Team")
                        .WithOne("MarketConfiguration")
                        .HasForeignKey("TeamService.Models.MarketConfiguration", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamService.Models.TeamAsset", b =>
                {
                    b.HasOne("TeamService.Models.Team", "Team")
                        .WithMany("TeamAssets")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamService.Models.TeamMembership", b =>
                {
                    b.HasOne("TeamService.Models.Team", "Team")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamService.Models.Team", b =>
                {
                    b.Navigation("MarketConfiguration");

                    b.Navigation("TeamAssets");

                    b.Navigation("TeamMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
